s="hello! sonali santosh yadav"
print("Original String ",s)
print("upper case :",s.upper())
print("Lower case :",s.lower())
print("Capitalize :",s.capitalize())
print("Swapcase :",s.swapcase())
print("isupper :",s.isupper())
print("islower :",s.islower())
print("Count :",s.count(s))
print("lenght of string :",len(s))
print("Title of string :",s.title())
print("find :",s.find("sonali"))
print("replace :",s.replace("sonali","sejal"))
print("split :",s.split())
print("Start with letter :",s.startswith("hello"))
print("End with letter:",s.endswith("byy"))